### ISSUE TITLE
About n=2t+1

### ISSUE THREAD

**Issue by mialuyao** [anbaccar/RSS_ring_ppml#1]
As mentioned in the paper: 
> For convenience and without loss of generality, we let n = 2t + 1.  When n > 2t + 1, 2t + 1 parties can carry out the computation on a reduced set of shares in such a way that there is no need to involve the remaining parties in the computation.

So, can I intuitively understand that: compared to an even number of participants, this scheme is more suitable for a setup with an odd number of participants?

Thank you！

**Comment by abaccarini** [comment]
Our constructions are based on the stipulation that there are an honest majority of participants. There is no benefit with respect to the collusion threshold if there are an even number of participants. E.g., for $n = 4$, we still can only allow for one corruption ($t=1$).
